sudo: required
services:
    - docker
before_install:
    - docker build -t skete/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true skete/docker-react npm run test
      
language: generic 