sudo: required
services:
    - docker
before_install:
    - docker build -t skete/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true skete/docker-react npm run test
      
language: generic 

'''
deploy:
    provider: elasticbeanstalk
    region: <whereever elastic beanstalk instance was created eg:"us-west">
    app: ""
    env: ""
    bucket_name: ""
    bucket_path: ""
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
'''
        